### ISSUE TITLE
Multiple Error Messages

### ISSUE THREAD

**Issue by awais-amjed** [ahangarha/Portfolio#14]
First of congratulations on creating such an awesome portfolio 🎉🎇

## Good Points 👍 
- Professional documentation ✔️ 
- Professional commit history  ✔️ 
- The project is deployed properly, and all pages, links, and images work as expected.   ✔️ 
- The page is responsive  ✔️ 
- Amazing animations  ✔️ 
- The pages should look identical to the original design    ✔️ 
- HTML is semantic  ✔️ 

## There is a small bug that you should consider fixing.

When the user clicks on the Submit Button multiple times and the email is not valid, multiple error messages are shown, which keep on stacking on top of each other. You can see it in the image below

![image](https://user-images.githubusercontent.com/73714615/151156342-cdb36c57-3aff-4696-bccf-cca4df583235.png)

A possible fix for this problem is to check if the "div" you are using to show the error message already exists, then don't generate another one. 

That's all, Have a good day and Happy coding!👏👏👏

**Comment by ahangarha** [comment]
Thanks for reporting the issue. I am working on it and will inform you as soon as it is fixed

**Comment by ahangarha** [comment]
Done! Thanks again.

**Comment by awais-amjed** [comment]
Great job fixing the issue 👏👏👏
