### ISSUE TITLE
reviewing 

### ISSUE THREAD

**Issue by saied2035** [ahangarha/Portfolio#9]
reviewing https://github.com/ahangarha/Portfolio/pull/8 : 

you realy did a great work 👏 . everything is great just one thing I can suggest that to make no scrollng when you oprn the mobile menu.

**Comment by Bavon101** [comment]
@ahangarha Nice work , 👌🐱‍💻Your menu drawer is better and more professional as per design. I think making one more change to the scroll ability, when the menu is open will push your site to the next level. 🐱‍🏍

**Comment by ahangarha** [comment]
Thank you my dear friends. I don't know why we  missed this scrolling issue and I am happy you noticed it in peer review session. Will work on it.

Have a good day

**Comment by ahangarha** [comment]
We just fixed this issue in today's task.
